[2024-05-29T17:03:21.860+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-29T17:03:21.979+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_1.task_4 scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-05-29T17:03:22.046+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_1.task_4 scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-05-29T17:03:22.053+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-29T17:03:22.219+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): task_4> on 2024-03-15 00:00:00+00:00
[2024-05-29T17:03:22.297+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=376) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-29T17:03:22.313+0000] {standard_task_runner.py:63} INFO - Started process 401 to run task
[2024-05-29T17:03:22.318+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'test_1', 'task_4', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpzrfw7xc1']
[2024-05-29T17:03:22.364+0000] {standard_task_runner.py:91} INFO - Job 72: Subtask task_4
[2024-05-29T17:03:22.812+0000] {task_command.py:426} INFO - Running <TaskInstance: test_1.task_4 scheduled__2024-03-15T00:00:00+00:00 [running]> on host 2832635d2b45
[2024-05-29T17:03:23.268+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_1' AIRFLOW_CTX_TASK_ID='task_4' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-05-29T17:03:23.298+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-29T17:03:23.309+0000] {logging_mixin.py:188} INFO - Run function_3!
[2024-05-29T17:03:23.330+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-29T17:03:23.344+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-29T17:03:23.382+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=test_1, task_id=task_4, run_id=scheduled__2024-03-15T00:00:00+00:00, execution_date=20240315T000000, start_date=20240529T170321, end_date=20240529T170323
[2024-05-29T17:03:23.529+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-29T17:03:23.648+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-29T17:03:23.680+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
