[2024-05-29T17:02:32.156+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-29T17:02:32.423+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_1.task_4 scheduled__2024-03-03T00:00:00+00:00 [queued]>
[2024-05-29T17:02:32.579+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_1.task_4 scheduled__2024-03-03T00:00:00+00:00 [queued]>
[2024-05-29T17:02:32.586+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-29T17:02:32.921+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): task_4> on 2024-03-03 00:00:00+00:00
[2024-05-29T17:02:32.976+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=253) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-29T17:02:33.041+0000] {standard_task_runner.py:63} INFO - Started process 293 to run task
[2024-05-29T17:02:33.032+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'test_1', 'task_4', 'scheduled__2024-03-03T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpbgwphw0y']
[2024-05-29T17:02:33.085+0000] {standard_task_runner.py:91} INFO - Job 33: Subtask task_4
[2024-05-29T17:02:33.546+0000] {task_command.py:426} INFO - Running <TaskInstance: test_1.task_4 scheduled__2024-03-03T00:00:00+00:00 [running]> on host 2832635d2b45
[2024-05-29T17:02:34.266+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_1' AIRFLOW_CTX_TASK_ID='task_4' AIRFLOW_CTX_EXECUTION_DATE='2024-03-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-03T00:00:00+00:00'
[2024-05-29T17:02:34.289+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-29T17:02:34.301+0000] {logging_mixin.py:188} INFO - Run function_3!
[2024-05-29T17:02:34.304+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-29T17:02:34.306+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-29T17:02:34.361+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=test_1, task_id=task_4, run_id=scheduled__2024-03-03T00:00:00+00:00, execution_date=20240303T000000, start_date=20240529T170232, end_date=20240529T170234
[2024-05-29T17:02:35.110+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-29T17:02:35.373+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-29T17:02:35.405+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
