[2024-05-29T17:02:07.645+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-29T17:02:08.702+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_1.task_1 scheduled__2024-03-14T00:00:00+00:00 [queued]>
[2024-05-29T17:02:08.928+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_1.task_1 scheduled__2024-03-14T00:00:00+00:00 [queued]>
[2024-05-29T17:02:08.949+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-29T17:02:09.230+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): task_1> on 2024-03-14 00:00:00+00:00
[2024-05-29T17:02:09.429+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=186) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-29T17:02:09.483+0000] {standard_task_runner.py:63} INFO - Started process 244 to run task
[2024-05-29T17:02:09.660+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'test_1', 'task_1', 'scheduled__2024-03-14T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp18so3q2d']
[2024-05-29T17:02:09.751+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask task_1
[2024-05-29T17:02:10.100+0000] {task_command.py:426} INFO - Running <TaskInstance: test_1.task_1 scheduled__2024-03-14T00:00:00+00:00 [running]> on host 2832635d2b45
[2024-05-29T17:02:10.964+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_1' AIRFLOW_CTX_TASK_ID='task_1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-14T00:00:00+00:00'
[2024-05-29T17:02:11.097+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-29T17:02:11.160+0000] {logging_mixin.py:188} INFO - Run function_1!
[2024-05-29T17:02:11.193+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-29T17:02:11.199+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-29T17:02:11.379+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=test_1, task_id=task_1, run_id=scheduled__2024-03-14T00:00:00+00:00, execution_date=20240314T000000, start_date=20240529T170208, end_date=20240529T170211
[2024-05-29T17:02:11.792+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-29T17:02:12.193+0000] {taskinstance.py:3498} INFO - 3 downstream tasks scheduled from follow-on schedule check
[2024-05-29T17:02:12.236+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
